# Generated by Django 4.2.11 on 2025-05-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='password',
            field=models.CharField(default='123456', max_length=128),
            preserve_default=False,
        ),
    ]
