version: "3"
services:
  db:
    image: mysql:8.0
    restart: always 
    environment:
      MYSQL_DATABASE: multitenant_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A multitenant_project worker --loglevel=info
    depends_on:
      - db
      - redis
